# Generated by Django 4.0.4 on 2022-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_genre_alter_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
